
default_job = "lint"
summary = false

[keybindings]
i = "job:install"


[jobs.lint]
command = ["ruffer", "--", "bin"]
need_stdout = true
watch = [
    ".gitignore",
    "./src",
    "./bin",
]

[jobs.format]
command = ["ruffer", "fix", "--", "bin"]
need_stdout = true
on_success = "back"

[jobs.install]
command = ["./install.sh", "h"]
need_stdout = true
on_success = "back"
