[classes]
sink = [
    # jabra micset
    "alsa_output.usb-GN_Netcom_A_S_Jabra_EVOLVE_20_MS_A00B1E6213020A-00.analog-stereo",
    # ugreen dock
    "alsa_output.usb-KTMicro_KT_USB_Audio_2021-07-19-0000-0000-0000--00.analog-stereo",
    # USB
    "alsa_output.usb-Generic_USB_Audio-00.analog-stereo",
    # mobo
    "alsa_output.pci-0000_00_1f.3-platform-skl_hda_dsp_generic.HiFi__Headphones__sink",
    "alsa_output.pci-0000_00_1f.3-platform-skl_hda_dsp_generic.HiFi__Speaker__sink",
    "alsa_output.pci-0000_00_1f.3.analog-stereo",
    "alsa_output.pci-0000_00_1b.0.analog-stereo",
]
source = [
    # jabra micset
    "alsa_input.usb-GN_Netcom_A_S_Jabra_EVOLVE_20_MS_A00B1E6213020A-00.mono-fallback",
    # lenovo webcam
    "alsa_input.usb-Vimicro_Corp._Lenovo_FHD_Webcam_Lenovo_FHD_Webcam_Audio-02.analog-stereo",
    # mobo
    "alsa_input.pci-0000_00_1f.3-platform-skl_hda_dsp_generic.HiFi__Mic1__source",
    "alsa_input.pci-0000_00_1f.3-platform-skl_hda_dsp_generic.HiFi__Mic2__source",
]
